// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIrd5QBprmL-q9hunnwhwdWyhsu39cEk',
    appId: '1:103180974870:web:b6b447f9616569505a6e37',
    messagingSenderId: '103180974870',
    projectId: 'learning-e8937',
    authDomain: 'learning-e8937.firebaseapp.com',
    storageBucket: 'learning-e8937.appspot.com',
    measurementId: 'G-ZX1TRPPCER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOjRcQva7zDry6zQONqY7I3StpM-6Qtc',
    appId: '1:103180974870:android:7cbca29ab86d65725a6e37',
    messagingSenderId: '103180974870',
    projectId: 'learning-e8937',
    storageBucket: 'learning-e8937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE3rY4gn_3EfclWfF5LWhAWXEO9ZlUC_A',
    appId: '1:103180974870:ios:7384a09d866b142d5a6e37',
    messagingSenderId: '103180974870',
    projectId: 'learning-e8937',
    storageBucket: 'learning-e8937.appspot.com',
    iosClientId: '103180974870-52h0mukte5ialijik3vvijbo629qn8jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sms',
  );
}
